### ISSUE TITLE
Scrolling stops on mobiles and tablets straight after installing meteor webix

### ISSUE THREAD

**Issue by mwarren2** [dandv/meteor-webix#15]
I installed webix with meteor so I could do CRUD on the database and it's been very good.
And since I was only doing stuff on my desktop I didn't notice this problem.

I just have to uninstall webix:webix and the problem with scrolling on non-desktops goes away. 
Reinstalling and it returns.

I can only suppose it's some kind of incompatibility with Bootstrap. Trouble is of course that we're talking about an SPA. So even though I only use Webix on some admin-only pages, it's present on every page.

**Comment by ghost** [comment]
``` javascript
Template.myTemplate.onRendered(function () {
  // This class prevents scrolling.
  // We don't want that for this page.
  $(document.body).removeClass('webix_full_screen');
  webix.Touch.disable();
});

Template.myTemplate.onDestroyed(function () {
  $(document.body).addClass('webix_full_screen');
  webix.Touch.enable();
});
```

**Comment by mwarren2** [comment]
Problem solved, thanks
