### ISSUE TITLE
Update to 2.4.7

### ISSUE THREAD

**Issue by rubenlagatie** [dandv/meteor-webix#16]
Could you please update webix to 2.4.7. I need some of the new features and bugfixes.

**Comment by rubenlagatie** [comment]
There is already a version 2.5 of webix now . If this repo is not being updated, i will be forced to remove it from my project.

**Comment by dandv** [comment]
The next update is planned for 2.5. Please see #3 regarding some confusion among repos. Ideas for how the Webix team and I can work better together would be great.

There are also some [licensing issues with publishing the Webix source code](https://github.com/webix-hub/tracker/issues/231).

**Comment by rudolfb** [comment]
See https://github.com/dandv/meteor-webix/issues/21#issuecomment-126966302 for steps to update the project or use it locally till @dandv finds time to update.

**Comment by dandv** [comment]
The package has been [updated to 2.5.0](https://github.com/dandv/meteor-webix/issues/21#issuecomment-130476998)!
