### ISSUE TITLE
Editing a property of a JSON object (i.e. Mongo Document)

### ISSUE THREAD

**Issue by KyleKing** [dandv/meteor-webix#18]
How does Webix work with objects/arrays (properties of a Mongo Document)?

For example, if I have this data format:

``` json
{
  "emails": [
    {
      "address": "email@email.com",
      "verified": false
    }
  ]
}
```

I can display it with:

``` js
columns: [
  ...
  { id: someID, map:"#emails[0].address#" };
  ...
]
```

However, I can't edit the email address in the proper location. If you edit the field as it is now, Webix updates the field from the id. So if the id was "address", there would be a new field called "address" with the edited string.

Is there a native way to link an object with an element in a Webix table?

**Comment by NorCalm** [comment]
By no means am I an expert - I just started learning Javascript and found Meteor/Webix crazy-easy to learn.

But how I've been pulling in a JSON file is to use the mongoimport program so that it becomes a Meteor collection (so you can use url property to load and save property to save), e.g.

webix.ui({
  view: 'datatable',
  autoconfig: true,
  editable: true,
  url:  webix.proxy('meteor', Emails.find()),
  save: webix.proxy('meteor', Emails)
});

I'm sure there's other ways to do this, but my JSON file is coming via ODBC so I already have to automate via a shell script anyway.

**Comment by KyleKing** [comment]
Thanks for responding! Yeah, I'm using the same technique to proxy the MondoDB data, which is really awesomely built; however, I'm having trouble with editing an object field using Webix's API.

So if you had a document like this:

``` json
{
  "name": "John",
  "stuff": ["part 1", "part 2", "part 3"],
  "moreStuff": {
    "phone": {
      "brand": "iphone",
      "version": 6,
      "valid": false
    }
  }
}
```

I can only display the field, "brand," but can't update it natively. With the code below, it creates a new field with the name brand (or whatever string is in the id field) rather than using the specific property created with the map setting.

``` json
{
  "name": "John",
  "stuff": ["part 1", "part 2", "part 3"],
  "moreStuff": {
    "phone": {
      "brand": "iphone",
      "version": 6,
      "valid": false
    }
  },
  "brand": "editedContent"
}
```

``` Js
var dataTable;

dataTable = {
  view: 'datatable',
  id: 'datatable',
  columns: [
    {
      id: 'someText',
      header: 'This is a brand',
      editor: 'text',
      fillspace: true,
      map: "#moreStuff.phone.brand#"
    }
  ],
  select: true,
  editable: true,
  editaction: 'dblclick',
  url: webix.proxy('meteor', Meteor.users),
  save: webix.proxy('meteor', Meteor.users)
};

// ---
// generated by coffee-script 1.9.2
```

Are you having the same issues? How would you display and edit the field "brand"?

**Comment by KyleKing** [comment]
If you're interested, I created a working example at: https://github.com/KyleKing/meteor-webix/tree/master/examples/crud-objects

Update: I've tried using the scheme setting, but Webix continues to fall back on the id property to update a document (relevant documentation: http://docs.webix.com/datatable__data_mapping.html)

**Comment by NorCalm** [comment]
@KyleKing I haven't had time to look at this, but I would suggest the use of Webix Snippet (http://webix.com/snippet/) to work through Webix issues.  It doesn't sound like it is much to do with Meteor yet so if you get your working example up on Snippet I think more folks (including me when I get a chance) will be able to interactively play with this.

Generally all of my datatable JSON objects are simple 2-d rows/columns without hierarchy.

**Comment by KyleKing** [comment]
Thanks for the suggestion! And whenever you have a chance, I started a snippet here: http://webix.com/snippet/9a29f390.  I'm not sure how to save/load the data in a snippet, but I created a variable and display it on the table

**Comment by KyleKing** [comment]
I'm switching to meteor-tabular, since it has the functions that I'm looking for.

If anyone else has the same issue, I found an older issue that looks like it should help fix this: https://github.com/dandv/meteor-webix/issues/5
