### ISSUE TITLE
Errors while adding packages

### ISSUE THREAD

**Issue by tarzak** [dandv/meteor-webix#2]
Hello, I have just tried to add your package in newly created meteor project, but it failed with this error:

> taras@taras-HP-ProBook-450-G0:~/job/webix-second-try$  meteor add webix:webix
>  => Errors while adding packages:             
> 
> While checking for webix:webix@2.2.3:
> error: No compatible build found

**Comment by funcoder** [comment]
Any chance you can update the package to support Meteor 1.0.3.1?

**Comment by alexedev** [comment]
The same here
