### ISSUE TITLE
Package version of webix:webix is wrong?

### ISSUE THREAD

**Issue by bartonhammond** [dandv/meteor-webix#24]
I am building my app using package based structure. 

I include 'webix:webix' and a skin.  When I look at the .meteor/local/build/programs/web.browser/packages/webix_webix.js, the header has this:

``` javascript
/*                                                                                                                     // 1
@license                                                                                                               // 2
webix UI v.2.3.8                                                                                                       // 3
This software is allowed to use under GPL or you need to obtain Commercial License                                     // 4
 to use it in non-GPL project. Please contact sales@webix.com for details                                              // 5
*/                                                                                                                     // 6
```

According to the docs, I was expecting 2.5.14

Any ideas?

**Comment by dandv** [comment]
I've tried to reproduce that both with a blank app and with the crud example from this repo, but webix_webix.js correctly shows 2.5.14.

Can you perhaps create a minimal reproduction repo?

**Comment by bartonhammond** [comment]
code: [https://github.com/bartonhammond/webix-packageversion](https://github.com/bartonhammond/webix-packageversion)

view live: http://webix-packageversion.meteor.com/

**Comment by bartonhammond** [comment]
Updated [package.js](https://github.com/bartonhammond/webix-packageversion/blob/master/packages/app-lib/package.js) with 

```
    'webix:webix@2.5.14'
```

**Comment by dandv** [comment]
Yeah, this is meteor's constraint solver at work. I filed a related ssue about that:

https://github.com/meteor/meteor/issues/4954
