### ISSUE TITLE
Meteor UserAccounts Webix project started

### ISSUE THREAD

**Issue by bartonhammond** [dandv/meteor-webix#26]
Opening this issue to bring this work to your attention and also I would like some help/advice on how to proceed w/ this project.
# 

To determine if Webix could be a "good citizen" in the Meteor ego-system, I thought I'd attempt to implement the UserAccounts package in Webix.

The current project is hosted here: http://useraccounts-webix.meteor.com

What works:
-  The nav bar switches routes (home, private (secured) and signon)
-  Iron-router integration
-  The sign on button is integrated w/ the core UserAccounts atNavButton
-  The sign on form displays per the UserAccounts core definitions

What doesn't work
-  The events from Webix controls to Meteor event system for the sign on form input fields
-  If I add the "atTitle" to the "atPwdForm", the "sign-in" page increases in size
-  Haven't added the "resize" event 

I've written up some thoughts of my design patterns, such as the choice to use Webix HTML Markup exclusively, and my current challenge, of which I am miserably failing, of mapping Webix events to Meteor events so that the UserAccounts core events can be emitted.

There's been significant success, imo, of seamlessly integrating Meteor templates with Webix markup - using this approach supports nested template interpolation, there are no limitations of using the Blaze template system.

You can read my overview of my design decisions at the [Meteor Webix UserAccounts package](https://github.com/bartonhammond/useraccounts-webix)

The [Meteor-Webix UserAccounts Boilerplate](https://github.com/bartonhammond/useraccounts-bootstrap-webix) project uses the package above.  To use it, local package development has to be set up (e.g. ln -s ..)

**Comment by dandv** [comment]
:100: !

**Comment by bartonhammond** [comment]
I am abandoning the project.  There's just too much core logic in the AccountsTemplates that I'm not able to use due to the components on the page are Webix and not Meteor.  

I tried using [meteor template extension(https://github.com/aldeed/meteor-template-extension) rather then the peer-libary:components but still no headway.  

Where I hit the wall was redirecting from signin <-> signup:  to show/hide the additional "password_again" field.  I created a "shadow" Meteor running in the same space to see what it was doing and of course, it was fine.  But the "at_pwd_form" would not display/hide the password field.  I give up.  

Not to say Meteor & Webix is not good, but not being able to easily include a working "UserAccounts" is going to slow the rate of adoption, imo.

**Comment by dandv** [comment]
Webix just [released v3.0 yesterday](http://webix.com/blog/webix-3-0-webix-jet-visual-designer-new-functionality/), along with a microframework called Webix Jet:

> Webix UI helps you to create apps faster by providing rich widgets. Still the whole app is more complex than just a set of widgets. Developers also need to arrange their code nicely as well as solve such tasks as app routing, state saving, code re-usage and etc. To cover all above concerns, we are introducing micro framework Webix Jet as part of the release. It will definitely save your time and efforts.

**Comment by dandv** [comment]
@bartonhammond: thanks for all your work on this, completed in #27. I'll try to make time to look at in depth next week, and integrated it into the demo.
