### ISSUE TITLE
Meteor Webix UserAccounts (v1.0.0)

### ISSUE THREAD

**Issue by bartonhammond** [dandv/meteor-webix#27]
Dan, I wanted to share this rewrite with you and get your opinion.  

It was far easier _not_ trying to shoehorn into Meteor User Accounts sub-system. 

This is fully functioning :relieved:
-barton
#### Meteor Webix UserAccounts

Features:
- [x]  Full integration with Templates  
- [x] Webix HTML Markup
- [x] Accounts Password
- [x]  Accounts Google
- [x] Email sent for Password Reset
- [x] Iron Router
- [x] Signin, Signup, ResetPassword, Changed Password Form Validatation

Live Functional Demo: [http://webix-account-boilerplate.meteor.com/](http://webix-account-boilerplate.meteor.com/)
Client Boilerplate Code: [https://github.com/bartonhammond/webix-account-boilerplate](https://github.com/bartonhammond/webix-account-boilerplate)
Meteor Webix User Account Package:[https://github.com/bartonhammond/webix-account](https://github.com/bartonhammond/webix-account)

[Client boilerplate](https://github.com/bartonhammond/webix-account-boilerplate)

<img src="http://giant.gfycat.com/EnlightenedYawningBlackcrappie.gif" width="348">

**Comment by dandv** [comment]
:100: :heart:

**Comment by bartonhammond** [comment]
I learned a lot about using Webix with Meteor and I expect anyone attempting this would benefit from my and your's experience.  Of course, I'm not totally done but there are significant design patterns I've discovered that will make my progress easier now.

I've started a GitBook where I review this code and explain my thoughts and design patterns.  Some people will want to just read the code while some others would appreciate some help.  

I hope that Meteor & Webix get's some more traction as it is truely a viable solution and much further advanced then any other widget library I've seen too.  Not having to do the tedious HTML & CSS is incredible for me as I don't have much design skills.

Here's a public link to the book with Disqus enabled.  If you'd rather open GitHub issues, that's fine.

https://www.gitbook.com/read/book/bartonhammond/meteor-and-webix?license=112db185e3a0

**Comment by bartonhammond** [comment]
fyi - i've been working w/ Maksim (support@webix) and have made numerous updates w/o keeping up w/ the gitbook yet.

One improvement is not having a modified webix.js.  now the boilerplate adds webix:webix

**Comment by bartonhammond** [comment]
Too many problems.

**Comment by dutu** [comment]
@bartonhammond is the **Meteor Webix UserAccounts** still available?

**Comment by bartonhammond** [comment]
@dutu No, it is not available.
