### ISSUE TITLE
More complex database queries

### ISSUE THREAD

**Issue by tarzak** [dandv/meteor-webix#5]
I have got my datatable and its data is in the array of document:

```
db.modules.findOne()

{
    "_id" : "12fbc238-5cf8-4863-a2f8-b5901e0ca0f2",
    "content" : "dataTable",
    "data" : [
        {
            "id" : 1,
            "title" : "The Shawshank Redemption",
            "year" : 1994,
            "votes" : 678790,
            "rating" : 9.2,
            "rank" : 1
        },
        {
            "id" : 2,
            "title" : "The Godfather",
            "year" : 1972,
            "votes" : 511495,
            "rating" : 9.2,
            "rank" : 2
        }
    ]
}
```

I need to build my datatable with this "inner" data. Is it possible?

> url:  webix.proxy('meteor', Modules.find({_id: "12fbc238-5cf8-4863-a2f8-b5901e0ca0f2"}).data)

Does not work :(.

looks like, if I want to place some data to the datatable, I need to store different documents in the collection for each row of datatable.

**Comment by ghost** [comment]
Not possible right now. I think for this kind of data it's better to store the data items as separate documents in a collection anyway. So you can do this right now.

**Comment by tarzak** [comment]
Whole document for simple row in a table? Pretty wierd... The same will be store point of the chart in a document. Then i need store, something kind of a parent-mark for every point/row, to know what document belongs which table, cause I will have many-many tables/charts. Collections will be huge...

**Comment by davidrea** [comment]
I'm still new to the MongoDB / no-SQL way of doing things, but as I
understand it the intent is to group data objects by-collection, and create
a new document for each row. Documents are linked together by their ID
fields.

The BulletProof Meteor guide has a section on data modeling:
https://bulletproofmeteor.com/database-modeling/

Cheers,
Dave

**Comment by ghost** [comment]
Both approaches are possible. It depends on your use case. The MongoDB documentation has good articles about data modeling: http://docs.mongodb.org/manual/core/data-modeling-introduction/.

@tarzak
If you want to keep your structure, you need to write a new proxy that does the right things on your structure. You can find the current proxy here:
https://github.com/dandv/webix-meteor-data/blob/meteor-integration/codebase/meteor-data.js

**Comment by mkozhukh** [comment]
@tarzak 
Check 
https://github.com/webix-hub/webix-meteor-example/blob/master/client/dataloading.js#L22
it shows how Template.autorun can be used to load data from any reactive source. You can use something like 

``` js
this.autorun(function(){
  var list = Modules.findOne("12fbc238-5cf8-4863-a2f8-b5901e0ca0f2");
  if (list)
     $$("dtable").parse(list.data);
});
```

**Comment by tarzak** [comment]
Thank you!
