### ISSUE TITLE
Errors when building package webix:webix

### ISSUE THREAD

**Issue by nicholas-gates** [dandv/meteor-webix#6]
These errors are reported when trying to run CRUD example:

Your app is crashing. Here's the latest log.

Started MongoDB.
Errors prevented startup:

While building package webix:webix:
error: File not found: webix/codebase/webix_debug.js
error: File not found: webix/codebase/webix.css
error: File not found: webix/codebase/fonts/PTS-webfont.eot
error: File not found: webix/codebase/fonts/PTS-webfont.ttf
error: File not found: webix/codebase/fonts/PTS-webfont.woff
error: File not found: webix/codebase/fonts/PTS-bold.eot
error: File not found: webix/codebase/fonts/PTS-bold.ttf
error: File not found: webix/codebase/fonts/PTS-bold.woff
error: File not found: webix-meteor-data/codebase/meteor-data.js

**Comment by pthom** [comment]
You need to download the submodules in the main folder

cd ../..
git submodule init
git submodule update

**Comment by dandv** [comment]
Thanks @pthom. @nickelstar, I've added instructions on how to run the example in [its README](https://github.com/dandv/meteor-webix/tree/master/examples/crud).
