### ISSUE TITLE
dataTable Widget Rendered Incorrectly on Mobile Devices

### ISSUE THREAD

**Issue by ybaror** [dandv/meteor-webix#7]
Issue with both Chrome and Safari on iPhone and iPad

**Comment by dandv** [comment]
The grid is rendered collapsed on any device actually.

This is odd. I hadn't changed anything since I deployed, and all resources are loaded from packages (not from the Webix CDN). The example works fine locally.

**Comment by dandv** [comment]
@mkozhukh: any ideas why this might happen? The table at http://webix.meteor.com/ is collapsed vertically, but [the example](https://github.com/dandv/meteor-webix/tree/master/examples/crud) works great locally.
